version: "3.8"

services:
  backend:
    image: node:22-slim
    ports:
      - 8000:8000
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: bash -c "apt-get update && apt-get install -y && npm i && npm start"
  frontend:
    image: node:22-slim
    working_dir: /app
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    env_file:
      - ./Frontend/.env
    restart: always
    command: bash -c "apt-get update && apt-get install -y && npm i && npm start"
